@csrf
<div class="grid gap-6 lg:grid-cols-2"><div class="space-y-5">
<label class="block font-semibold">Title<input name="title" value="{{ old('title',$livestream->title ?? '') }}" class="mt-2 w-full rounded-xl border-slate-300" required></label>
<label class="block font-semibold">Subtitle<input name="subtitle" value="{{ old('subtitle',$livestream->subtitle ?? '') }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="block font-semibold">Speaker<input name="speaker" value="{{ old('speaker',$livestream->speaker ?? '') }}" class="mt-2 w-full rounded-xl border-slate-300"></label><label class="block font-semibold">Series<input name="series" value="{{ old('series',$livestream->series ?? '') }}" class="mt-2 w-full rounded-xl border-slate-300"></label></div>
<label class="block font-semibold">Description<textarea name="description" rows="8" class="mt-2 w-full rounded-xl border-slate-300">{{ old('description',$livestream->description ?? '') }}</textarea></label>
</div><div class="space-y-5">
<div class="grid gap-4 sm:grid-cols-2"><label class="block font-semibold">Platform<select name="platform" class="mt-2 w-full rounded-xl border-slate-300">@foreach(\App\Models\Livestream::PLATFORMS as $value=>$label)<option value="{{ $value }}" @selected(old('platform',$livestream->platform ?? 'youtube')===$value)>{{ $label }}</option>@endforeach</select></label><label class="block font-semibold">Status override<select name="manual_status" class="mt-2 w-full rounded-xl border-slate-300"><option value="automatic" @selected(old('manual_status',$livestream->manual_status ?? 'automatic')==='automatic')>Automatic</option><option value="live" @selected(old('manual_status',$livestream->manual_status ?? '')==='live')>Live now</option><option value="ended" @selected(old('manual_status',$livestream->manual_status ?? '')==='ended')>Ended</option></select></label></div>
<label class="block font-semibold">Stream link<input type="url" name="stream_url" value="{{ old('stream_url',$livestream->stream_url ?? '') }}" class="mt-2 w-full rounded-xl border-slate-300" required><span class="mt-1 block text-xs text-slate-500">YouTube and Facebook links embed automatically. Zoom and custom links open externally.</span></label>
<label class="block font-semibold">Thumbnail or poster<input type="file" name="thumbnail" accept=".jpg,.jpeg,.png,.webp" class="mt-2 w-full rounded-xl border p-3"></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="block font-semibold">Starts<input type="datetime-local" name="scheduled_start" value="{{ old('scheduled_start',isset($livestream)&&$livestream->scheduled_start?$livestream->scheduled_start->format('Y-m-d\\TH:i'):'') }}" class="mt-2 w-full rounded-xl border-slate-300"></label><label class="block font-semibold">Ends<input type="datetime-local" name="scheduled_end" value="{{ old('scheduled_end',isset($livestream)&&$livestream->scheduled_end?$livestream->scheduled_end->format('Y-m-d\\TH:i'):'') }}" class="mt-2 w-full rounded-xl border-slate-300"></label></div>
<label class="block font-semibold">Display order<input type="number" min="0" name="sort_order" value="{{ old('sort_order',$livestream->sort_order ?? 0) }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
<div class="grid gap-3 sm:grid-cols-2">@foreach([['is_featured','Featured broadcast'],['show_on_homepage','Show on homepage'],['is_published','Published']] as [$field,$label])<label class="flex gap-3 rounded-xl border p-3"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$livestream->{$field} ?? false))><span>{{ $label }}</span></label>@endforeach</div>
</div></div>
<div class="mt-8 flex gap-3"><button class="rounded-xl bg-[#072f68] px-5 py-3 font-bold text-white">{{ $buttonText }}</button><a href="{{ route('admin.livestreams.index') }}" class="rounded-xl border px-5 py-3">Cancel</a></div>
