<x-admin-layout title="Campuses | RHMI CMS" heading="Campuses">
<div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-2xl font-bold text-[#072f68]">Church Campuses</h2><p class="mt-1 text-sm text-slate-600">Manage locations, resident pastors, contacts, service times and photos.</p></div><a href="{{ route('admin.campuses.create') }}" class="rounded-xl bg-lime-500 px-5 py-3 font-bold text-[#072f68]">+ Add Campus</a></div>
@if(session('success'))<div class="mb-5 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-green-800">{{ session('success') }}</div>@endif
@if($campuses->isEmpty())<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center">No campuses yet.</div>@else
<div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">@foreach($campuses as $campus)
<article class="overflow-hidden rounded-2xl border bg-white shadow-sm">
@if($campus->cover_image_url)<img src="{{ $campus->cover_image_url }}" class="h-52 w-full object-cover">@else<div class="grid h-52 place-items-center bg-gradient-to-br from-[#072f68] to-[#0d5fa8] p-6 text-center text-xl font-bold text-white">{{ $campus->name }}</div>@endif
<div class="p-5"><div class="mb-3 flex items-start justify-between gap-3"><h3 class="font-bold text-[#072f68]">{{ $campus->name }}</h3><div class="flex flex-col gap-1">@if($campus->is_main_campus)<span class="rounded-full bg-lime-100 px-2.5 py-1 text-xs font-semibold text-lime-700">Main Campus</span>@endif<span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $campus->is_published?'bg-green-100 text-green-700':'bg-slate-100 text-slate-600' }}">{{ $campus->is_published?'Published':'Draft' }}</span></div></div>
<p class="text-sm text-slate-600">{{ $campus->address }}</p>@if($campus->resident_pastor)<p class="mt-2 text-sm text-slate-500"><strong>Resident Pastor:</strong> {{ $campus->resident_pastor }}</p>@endif
<div class="mt-5 flex gap-2"><a href="{{ route('admin.campuses.edit',$campus) }}" class="flex-1 rounded-lg border border-blue-200 px-4 py-2 text-center text-sm font-semibold text-blue-700">Edit</a><form method="POST" action="{{ route('admin.campuses.destroy',$campus) }}" class="flex-1" onsubmit="return confirm('Delete this campus permanently?')">@csrf @method('DELETE')<button class="w-full rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Delete</button></form></div></div>
</article>@endforeach</div><div class="mt-6">{{ $campuses->links() }}</div>@endif
</x-admin-layout>
