@csrf
<div class="grid gap-6 lg:grid-cols-2">
<div class="space-y-5">
<div><label class="mb-2 block font-semibold">Title</label><input name="title" value="{{ old('title',$libraryResource->title ?? '') }}" class="w-full rounded-xl border-slate-300" required></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-2 block font-semibold">Author</label><input name="author" value="{{ old('author',$libraryResource->author ?? '') }}" class="w-full rounded-xl border-slate-300"></div><div><label class="mb-2 block font-semibold">Type</label><select name="resource_type" class="w-full rounded-xl border-slate-300">@foreach(\App\Models\LibraryResource::TYPES as $value=>$label)<option value="{{ $value }}" @selected(old('resource_type',$libraryResource->resource_type ?? 'book')===$value)>{{ $label }}</option>@endforeach</select></div></div>
<div><label class="mb-2 block font-semibold">Category</label><select name="library_category_id" class="w-full rounded-xl border-slate-300"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('library_category_id',$libraryResource->library_category_id ?? '')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div><label class="mb-2 block font-semibold">Description</label><textarea name="description" rows="9" class="w-full rounded-xl border-slate-300">{{ old('description',$libraryResource->description ?? '') }}</textarea></div>
</div>
<div class="space-y-5">
<div><label class="mb-2 block font-semibold">Cover image</label><input type="file" name="cover" accept=".jpg,.jpeg,.png,.webp" class="w-full rounded-xl border p-3">@if(isset($libraryResource)&&$libraryResource->cover_url)<img src="{{ $libraryResource->cover_url }}" class="mt-3 h-48 rounded-xl object-cover">@endif</div>
<div><label class="mb-2 block font-semibold">PDF file</label><input type="file" name="file" accept=".pdf" class="w-full rounded-xl border p-3"><p class="mt-1 text-xs text-slate-500">Maximum 100 MB.</p></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-2 block font-semibold">Price (UGX)</label><input type="number" min="0" name="price_ugx" value="{{ old('price_ugx',$libraryResource->price_ugx ?? 0) }}" class="w-full rounded-xl border-slate-300"></div><div><label class="mb-2 block font-semibold">Display order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$libraryResource->sort_order ?? 0) }}" class="w-full rounded-xl border-slate-300"></div></div>
<div class="grid gap-3 sm:grid-cols-2">@foreach([['is_paid','Paid resource'],['allow_read_online','Allow online reading'],['allow_download','Allow download'],['is_featured','Featured'],['is_published','Published']] as [$field,$label])<label class="flex gap-3 rounded-xl border p-3"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$libraryResource->{$field} ?? ($field==='allow_read_online'||$field==='allow_download')))><span>{{ $label }}</span></label>@endforeach</div>
</div></div>
<div class="mt-8 flex gap-3"><button class="rounded-xl bg-[#072f68] px-5 py-3 font-bold text-white">{{ $buttonText }}</button><a href="{{ route('admin.library-resources.index') }}" class="rounded-xl border px-5 py-3">Cancel</a></div>
