<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
if(!Schema::hasTable('about_settings')){Schema::create('about_settings',function(Blueprint $t){$t->id();$t->string('story_heading')->nullable();$t->longText('story_body')->nullable();$t->string('vision_heading')->default('Our Vision');$t->longText('vision_body')->nullable();$t->string('mission_heading')->default('Our Mission');$t->longText('mission_body')->nullable();$t->string('motto')->nullable();$t->longText('motto_explanation')->nullable();$t->timestamps();});DB::table('about_settings')->insert(['id'=>1,'story_heading'=>'A ministry grounded in the Word and led by the Spirit','story_body'=>'Revelation Hour Ministries International proclaims Jesus Christ, disciples believers, strengthens families and serves communities through biblical teaching, prayer, worship and compassionate outreach.','vision_heading'=>'Our Vision','mission_heading'=>'Our Mission','created_at'=>now(),'updated_at'=>now()]);}
if(!Schema::hasTable('core_values')){Schema::create('core_values',function(Blueprint $t){$t->id();$t->string('title',150);$t->text('description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_published')->default(true);$t->timestamps();});}
if(!Schema::hasTable('leaders')){Schema::create('leaders',function(Blueprint $t){$t->id();$t->string('name',150);$t->string('role',150);$t->string('department',150)->nullable();$t->longText('biography')->nullable();$t->string('photo_path')->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->string('facebook_url')->nullable();$t->string('instagram_url')->nullable();$t->string('x_url')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_published')->default(true);$t->timestamps();});}
if(!Schema::hasTable('service_times')){Schema::create('service_times',function(Blueprint $t){$t->id();$t->string('name',150);$t->string('day',20);$t->time('start_time');$t->time('end_time')->nullable();$t->text('description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_published')->default(true);$t->timestamps();});DB::table('service_times')->insert([
['name'=>'Bible Study','day'=>'Tuesday','start_time'=>'18:00:00','end_time'=>'20:00:00','sort_order'=>10,'is_published'=>1,'created_at'=>now(),'updated_at'=>now()],
['name'=>'MCs','day'=>'Thursday','start_time'=>'19:30:00','end_time'=>null,'sort_order'=>20,'is_published'=>1,'created_at'=>now(),'updated_at'=>now()],
['name'=>'Camp Meeting','day'=>'Friday','start_time'=>'18:00:00','end_time'=>'22:00:00','sort_order'=>30,'is_published'=>1,'created_at'=>now(),'updated_at'=>now()],
['name'=>'Business Service','day'=>'Sunday','start_time'=>'09:00:00','end_time'=>'11:00:00','sort_order'=>40,'is_published'=>1,'created_at'=>now(),'updated_at'=>now()],
['name'=>'Sunday Service','day'=>'Sunday','start_time'=>'11:00:00','end_time'=>'13:00:00','sort_order'=>50,'is_published'=>1,'created_at'=>now(),'updated_at'=>now()]]);}}
public function down():void{Schema::dropIfExists('service_times');Schema::dropIfExists('leaders');Schema::dropIfExists('core_values');Schema::dropIfExists('about_settings');}};
